### ISSUE TITLE
Project Spec - Spec - Infrastructure - Web Host Section

### ISSUE THREAD

**Issue by hughesd22** [hughesd22/study-up-pup#20]

**Comment by hughesd22** [comment]
Currently have no staging servers. Will need to confirm whether this app should or not

**Comment by hughesd22** [comment]
Currently have placeholders for Staging Servers in spec.md, but will need to update by either removing these placeholders or adding links to staging servers depending on instructor's feedback prior to closing this issue.

**Comment by reactivepixel** [comment]
Also, I really like the use of the Help Wanted Label. Bonus points!
