### ISSUE TITLE
Develop is behind Master, but no differences

### ISSUE THREAD

**Issue by hughesd22** [hughesd22/study-up-pup#3]
1. I merged the release-1.0 branch into master using the Pull Request [Release 1.0](https://github.com/hughesd22/study-up-pup/pull/2). I believe this created a commit object on master that isn't present on develop.  

2. I made some changes to the README on GitHub, forgetting to use the correct feature branch workflow for changes. This resulted in a direct commit to master which doesn't exist on develop.

3. I reverted this direct change to master using "git revert SHA" which I believe created a commit object on master that isn't present on develop.

4. I am now seeing "This branch is 3 commits behind master" when I look at the develop branch on GitHub. [View Image](https://i.imgur.com/EndY6sV.png)

5. When I compare differences or click "Pull Request" I am shown that there are no differences between master and develop. [View Image](https://i.imgur.com/eDOooZS.png)

If there are no differences, why am I seeing that develop is X commits behind master? And more importantly, how do I solve this so I can continue working on Milestone 1: Pivot?

**Comment by markmichon** [comment]
@hughesd22 It looks like develop ended up behind master. I'm basing the following off the assumption that your local state is in sync with github's. 

You can resolve this by merging master into develop (switch to develop, then `git merge master`). That will bring develop back in line with master.

**Comment by hughesd22** [comment]
@markmichon Okay. I wasn't sure if I was allowed to merge master into develop to fix this. Thanks!

**Comment by markmichon** [comment]
Great. Make sure to push the updated develop up to github 👍
